# version: '3.8'

# services:
#   rabbitmq:
#     image: rabbitmq:3.12-management
#     ports:
#       - "5672:5672"   # AMQP port
#       - "15672:15672" # Management UI
#     environment:
#       RABBITMQ_DEFAULT_USER: guest
#       RABBITMQ_DEFAULT_PASS: guest
#       RABBITMQ_ERLANG_COOKIE: "supersecretcookie" # Explicitly set the cookie
#       UMASK: "0077" # Ensures files are created with 600 permissions
#     volumes:
#       - rabbitmq_data:/var/lib/rabbitmq
#     user: "100:101" # Force RabbitMQ user/group (UID/GID from official image)
#     command: sh -c "mkdir -p /var/lib/rabbitmq && touch /var/lib/rabbitmq/.erlang.cookie && chmod 600 /var/lib/rabbitmq/.erlang.cookie && chown 100:101 /var/lib/rabbitmq/.erlang.cookie && docker-entrypoint.sh rabbitmq-server"

# volumes:
#   rabbitmq_data:

version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge